### ISSUE TITLE
Its not working like the Usage model States

### ISSUE THREAD

**Issue by FerchoCarcho** [shhdgit/vue-easy-slider#2] opened 2016-08-13 22:08 UTC
Hello @shhdgit  and Thank you for this component.
I have tried the following

```
        <slider width="auto" height="400px" :interval="1000">
            <slider-item v-for="slide in slides">
                    <img :src="slide.image_path">
                    <p>{{slide.message}}</p>
            </slider-item>
        </slider>
```

But It only gives 
[image](https://s3.postimg.org/4ofd89uo3/Untitled_1.jpg)
As you can see in the image the data is fetched correctly but it is not being displayed properly, 
I hard coded the width of the slide-content and the image is showed but if i hit the "next button" no other images are being displayed.

If the component wouldn’t be compiled i would try to debug it.

Please take a look at it.

Thank you very much.

**Comment by FerchoCarcho** [comment] 2016-08-13 23:11
It works like:

```
<slider-item ><img :src="slides[0].image_path"> </slider-item>
<slider-item ><img :src="slides[1].image_path"> </slider-item>
<slider-item ><img :src="slides[2].image_path"> </slider-item>
```

But Isnt ideal when you dont know how many items you have in your data object.

**Comment by FerchoCarcho** [comment] 2016-08-13 23:22
Also It would be very good if you could have the following 2 improvements:
. Make the sliding direction just one way, because you know when it reaches to the end it rewinds to the start and that is very distracting. 
. Would it be possible to make a Fade in - fade out effect instead of sliding, It is smoother for the eyes. and more pleasant to watch.

**Comment by shhdgit** [comment] 2016-08-14 05:56
Sorry for the confusion but i can't reproduce the bug even in firefox.

here is my demo

```
<body>
  <slider>
    <slider-item v-for="slider in sliders" :style="{ backgroundColor: '#3f51b5' }">
      <img :src="slider.src">
    </slider-item>
  </slider>
</body>
```

```
    new Vue( {
      el: 'body',
      components: {
        'Slider': window[ 'vue-easy-slider' ].Slider,
        'SliderItem': window[ 'vue-easy-slider' ].SliderItem
      },
      data: {
        sliders: [
          { src: './avatar.jpg', text: '123' },
          { src: './avatar.jpg', text: '456' },
          { src: './avatar.jpg', text: '789' },
          { src: './avatar.jpg', text: '123' }
        ]
      }
    } )
```

Can you help me.
And I want add more effect and option latter.Thanks for the issue!

**Comment by FerchoCarcho** [comment] 2016-08-14 13:17
Im Not an expert but I will debug It and post What I have found.

**Comment by FerchoCarcho** [comment] 2016-08-14 18:20
@shhdgit If you give the Slide component an array of objects you get the children length as 0.
![untitled-1](https://cloud.githubusercontent.com/assets/11180135/17650985/2db79d72-622a-11e6-8d21-98da12b93bff.jpg)
EDIT: The hardcoded Array on Data also works for me.
but when I fetch the data object from the database on Ready or Route, Created , It doesnt produce any children Even they are showed as `<slider-item>`childs correctly at the browser Inspector.

**Comment by shhdgit** [comment] 2016-08-15 04:23
Gotcha, i'll try : D happy hacking!

**Comment by FerchoCarcho** [comment] 2016-08-15 13:16
If you can , try to check this Slider component from [Yuche](https://github.com/yuche/vue-strap/blob/master/src/Slider.vue). It is more complicated than yours but it has many interesting Procedures, maybe you can find the solution there. Im trying too. Specially the. `this.$parent.$children`

**Comment by shhdgit** [comment] 2016-08-15 13:48
@FerchoCarcho Thanks! Now Fixed the 0px bug. Try `npm update vue-easy-slider`

**Closed as completed** 2016-08-15 13:49 UTC
Labels: bug, help wanted

**Comment by shhdgit** [comment] 2016-08-15 13:54
I'll Add more effect soon.  : D

**Comment by FerchoCarcho** [comment] 2016-08-15 14:31
@shhdgit  THANK YOU for fixing it so quick! This component is Excellent :+1: . Congratulations and Keep the good work On! Btw. I would like to know why this.$children was empty. It should contain n objects when called asyncronusly.

**Comment by shhdgit** [comment] 2016-08-16 05:32
this.$children was not empty. My code is bad-smelling now. I should improve some procedures.
